# -*- coding: utf-8 -*-
"""Positive numbers in a range.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-ogqFzz6VLFuJhgktio9HDr4njmo5hli
"""

start = int(input('Enter the start of the range: '))
end = int(input('Enter the end of the range: '))
for num in range(start, end+1):
    if num >= 0:
        print(num, end = " ")