# -*- coding: utf-8 -*-
"""SetOperations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LQI8li5DjrkX09kQxbF09HsYdDpAuS4v
"""

A = {0,2,4,6,8,10}
B = {1,2,3,4,5,6}

print('Union of A and B is ',A | B)

print('Intersection of A and B is ',A & B)

print('Difference of A and B is ',A-B)

print('Symmetric Difference of A and B is ',A^B)