# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/124uDS1C4E8t15_Bk0rPXU7q_ioqmPh8Y
"""

c=0
f1 = 0
f2 = 1
n = int(input("Enter a number "))
print(f1)
print(f2)
while c<=n:
  c = f1 + f2
  print(c)
  f1=f2
  f2=c